# Templates
node: &NODE_JS
  - patterns: &JS_FILES_PATTERN
      - "**/package.json"
    commands: &YARN_INSTALL
      - yarn install

rust_test: &RUST_TEST
  - patterns: &RUST_PATTERN
      - "**/*.rs"
    commands: &SLEEPY
      - sleep 1; echo 'slept 1 second'
      - sleep 2; echo 'slept for 2 seconds'
rust_test_failure: &RUST_TEST_FAILURE
  - patterns: *RUST_PATTERN
    commands:
      - sleep 1; echo "slept 1 second"
      - sleep 2; echo "slept 2 seconds, erroring"; exit 1;
      - sleep 3; echo "slept 3 seconds";

# Hooks

# Post checkout is the only supported hook for now
post-checkout: *RUST_TEST

# Test Hooks
update: *RUST_TEST_FAILURE
