# Templates
node: &NODE_JS
  - patterns: &JS_FILES_PATTERN
      - "**/package.json"
    commands: &YARN_INSTALL
      - yarn install

rust_test: &RUST_SLEEP_TEST
  - patterns: &RUST_PATTERN
      - "**/*.rs"
    commands: &SLEEPY
      - sleep 1; echo 'slept 1 second'
      - sleep 2; echo 'slept for 2 seconds'
  - patterns: *RUST_PATTERN
    commands: &SLEEPY
      - sleep 2; echo 'slept for 2 seconds for the second times'
rust_test_failure: &RUST_TEST_FAILURE
  - patterns:
      - "**/*"
    commands:
      - sleep 1; echo "slept 1 second"
      - sleep 2; echo "slept 2 seconds, erroring"; exit 1;
      - sleep 3; echo "slept 3 seconds";

cargo_test: &CARGO_TEST
  - patterns:
      - "**/*.rs"
    commands:
      - make test;
# Hooks
hooks:
  pre-push: *CARGO_TEST
  pre-commit: *CARGO_TEST

  post-checkout: *RUST_SLEEP_TEST

  # Test Hooks
  update: *RUST_TEST_FAILURE
  # applypatch-msg: *BASIC_HOOK_COMMAND
  # pre-applypatch: *BASIC_HOOK_COMMAND
  # post-applypatch: *BASIC_HOOK_COMMAND
  # pre-commit: *BASIC_HOOK_COMMAND
  # prepare-commit-msg: *BASIC_HOOK_COMMAND
  # commit-msg: *BASIC_HOOK_COMMAND
  # post-commit: *BASIC_HOOK_COMMAND
  # pre-rebase: *BASIC_HOOK_COMMAND
  # post-checkout: *BASIC_HOOK_COMMAND
  # post-merge: *BASIC_HOOK_COMMAND
  # pre-push: *BASIC_HOOK_COMMAND
  # pre-receive: *BASIC_HOOK_COMMAND
  # update: *BASIC_HOOK_COMMAND
  # post-receive: *BASIC_HOOK_COMMAND
  # post-update: *BASIC_HOOK_COMMAND
  # push-to-checkout: *BASIC_HOOK_COMMAND
  # pre-auto-gc: *BASIC_HOOK_COMMAND
  # post-rewrite: *BASIC_HOOK_COMMAND
  # rebase: *BASIC_HOOK_COMMAND
  # sendemail-validate: *BASIC_HOOK_COMMAND
  # fsmonitor-watchman: *BASIC_HOOK_COMMAND
