# Templates
node: &NODE_JS
  - patterns: &JS_FILES_PATTERN
      - "**/package.json"
    commands: &YARN_INSTALL
      - yarn install

rust_test: &RUST_SLEEP_TEST
  - patterns: &RUST_PATTERN
      - "**/*.rs"
    commands: &SLEEPY
      - sleep 1; echo 'slept 1 second'
      - sleep 2; echo 'slept for 2 seconds'
  - patterns: *RUST_PATTERN
    commands: &SLEEPY
      - sleep 2; echo 'slept for 2 seconds for the second times'
rust_test_failure: &RUST_TEST_FAILURE
  - patterns: *RUST_PATTERN
    commands:
      - sleep 1; echo "slept 1 second"
      - sleep 2; echo "slept 2 seconds, erroring"; exit 1;
      - sleep 3; echo "slept 3 seconds";

cargo_test: &CARGO_TEST
  - patterns:
      - "**/*.rs"
    commands:
      - cargo test;
# Hooks

pre-push: *CARGO_TEST
pre-commit: *CARGO_TEST

post-checkout: *RUST_SLEEP_TEST
post-commit: *RUST_SLEEP_TEST

# Test Hooks
update: *RUST_TEST_FAILURE
