os:
  - linux
  - osx
language: rust
rust:
  - 1.32.0
cache: cargo
before_install:
  - openssl aes-256-cbc -K $encrypted_423875454745_key -iv $encrypted_423875454745_iv
    -in signing-key.gpg.enc -out signing-key.gpg -d

script:
  - make build
  - cargo test

deploy:
  provider: releases
  api_key:
    secure: "oH0QoBn3LR1MI56xWd7AKgVhvPxkJod4rNslM2aPy3ZMEx+sYkWG9WmnISXuztMBwdI3C6zj2jmg8YOB+IKI6n0MOzKCjgOa9A4FdMOmrCLMB0soNhGdEW385UKpjEPHynYGJTOIPsbcu8i3THpkKYmxXhCUOblt7f7h+N9PVTmiBBmobKk/M8ZGsI0ddnDR0DHuUAC83q+8ZGjVR7mQe15a42MqJkV26XUpGYpMJNmhc3rpOGdKUE+foX7Yj+yoCzuMglgXJMlULJO0WrdY3+3qAoPR3EgV7gwKsd5Eyp+ZCxBA168i+QT9ZlWGHtSiQAtPX6yY7prvlMR1g+48yXFP90YJGT6jeP7SEmH9uFlBW4FcJ/vQ65Oj16ImvwAbvv9aaZPLjlSQIClFQpDxO3ZLS2ffHOMpvU0gIbJZfT7iMXNN/RSKfz246B23kxcqfOQ46aSBOi7MnTalQH6uwerl30aZ84bCtCfec+eZP7Htmvf/cmeNKlf5LGEtBY0jW6Y84aAC+G+1YeQIKUm88qhPuLfY7elja4uJT1vzpLlcBbGTzorctT6uiFi4G2PvPixWNRphJ4eZc/AmKszRA2fvo7a7s2vzZKDcRRktS5ls1HF4u3Xa04HDzxyyMrVnBSE3zgi5aKMZFprhPPpa9qV/tBK1GTCFj61I2GWNv+c="
  file: "build/*"
  skip_cleanup: true
  on:
    tags: true
  draft: true
