[package]
name = "git_file_hooks"
version = "1.0.0"
authors = ["Eric Wooley <ericwooley@gmail.com>"]
edition = "2018"
[profile.release]
lto=true
panic="abort"
[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
glob = "0.2"
run_script = "0.2.5"